# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Jiaqing Zhang
google_analytics: Jiaqing Zhang
title: Jiaqing Zhang

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jiaqing Zhang

description: Stylish Jekyll Theme
author:
  name: Jiaqing Zhang
  email: jqzhang_2@stu.xidian.edu.cn
  github: icey-zhang
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Avengers Assemble!!!
  # 修改个签请去sidebar.html里改
  # email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
# categories_path: categories.html
# tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
